version: '2'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs-docker-test
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      SERVER_PORT: 8080
    command: node server.js
